// Generated by Wrangler by running `wrangler types runs/form-stage1-implementation/worker-configuration.d.ts --config runs/form-stage1-implementation/wrangler.json --strict-vars=false`

interface Env {
	ENQUIRIES_ENABLED: string;
	TURNSTILE_SITE_KEY: string;
	ALLOWED_HOSTS: string;
	RETENTION_DAYS: string;
	TURNSTILE_SECRET_KEY: string;
	RATE_LIMIT_SECRET: string;
	DB: D1Database;
	ASSETS: Fetcher;
}
