/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.api.json --include-runtime=false --strict-vars=false` (hash: 3ef4ae3af6c423ac21b25cd5c30c8a5d)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
	ENQUIRIES_ENABLED: string;
	TURNSTILE_SITE_KEY: string;
	ALLOWED_HOSTS: string;
	RETENTION_DAYS: string;
	NOTIFICATIONS_ENABLED: string;
	NOTIFICATIONS_START_AT: string;
	ZOHO_REGION: string;
	ZOHO_ACCOUNT_ID: string;
	NOTIFICATION_FROM: string;
	NOTIFICATION_TO: string;
	TURNSTILE_SECRET_KEY: string;
	RATE_LIMIT_SECRET: string;
	ZOHO_CLIENT_ID: string;
	ZOHO_CLIENT_SECRET: string;
	ZOHO_REFRESH_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
